- hosts: master
  become: yes
  tasks: 
    - name: copy get_helm
      copy:
        src: /root/demo/get_helm.sh
        dest: /root/get_helm.sh
        mode: '0700'
        
    - name: run get_helm.sh
      shell: /root/get_helm.sh 
      
    - name: git clone csi-vxflex
      git:
        repo: https://github.com/dell/csi-vxflexos
        dest: /home/jono/csi-vxflex/
        accept_hostkey: yes
        key_file: /home/jono/.ssh/id_rsa
      become: yes
      become_user: jono
           
    - name: create vxflexos namespace
      become: yes
      become_user: jono
      shell: kubectl create namespace vxflexos
      
    - name: modify secret.yaml
      lineinfile:
        path: /home/jono/csi-vxflex/helm/secret.yaml
        regexp: '{{item.From}}'
        line: '{{item.To}}'
      with_items:
        - { From: '  username: bm90X3RoZV91c2VybmFtZQ==', To: '  username: YWRtaW4=' }
        - { From: '  password: bm90X3RoZV9wYXNzd29yZA==', To: '  password: U2NhbGVpbzEyMw==' }
     
    - name: apply secret to system
      become: yes
      become_user: jono
      shell: kubectl apply -f /home/jono/csi-vxflex/helm/secret.yaml 

    - name: copy 'myvalues.yaml' file
      copy:
        src: /home/jono/csi-vxflex/helm/csi-vxflexos/values.yaml
        dest: /home/jono/csi-vxflex/helm/myvalues.yaml
        remote_src: yes
  
    - name: modify 'myvalues.yaml' file
      lineinfile:
        path: /home/jono/csi-vxflex/helm/myvalues.yaml
        regexp: '{{item.From}}'
        line: '{{item.To}}'
      with_items:
        - { From: 'systemName: systemname', To: 'systemName: PowerFlex-SantaClara' }
        - { From: 'restGateway: https://123.0.0.1', To: 'restGateway: https://10.213.121.40' }
        - { From: 'storagePool: sp', To: 'storagePool: SP-MG-1' }
    
    - name: modify 'mdmIP'
      replace:
        path: /home/jono/csi-vxflex/helm/myvalues.yaml
        regexp: 'mdmIP:\n  - 0.0.0.0\n  - 0.0.0.0\n'
        replace: 'mdmIP: 10.172.1.11,20.172.1.11,10.172.1.12,20.172.1.12'    
    
#    - name: modify 'snapshot.storage.k8s.io_volumesnapshotclasses.yaml' file
#      lineinfile:
#        path: /home/jono/csi-vxflex/dell-csi-helm-installer/beta-snapshot-crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
#        regexp: '{{item.From}}'
#        line: '{{item.To}}'
#      with_items:
#        - { From: 'apiVersion: apiextensions.k8s.io/v1beta1', To: 'apiVersion: apiextensions.k8s.io/v1' }
    
#    - name: modify 'snapshot.storage.k8s.io_volumesnapshotcontents.yaml' file
#      lineinfile:
#        path: /home/jono/csi-vxflex/dell-csi-helm-installer/beta-snapshot-crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
#        regexp: '{{item.From}}'
#        line: '{{item.To}}'
#      with_items:
#        - { From: 'apiVersion: apiextensions.k8s.io/v1beta1', To: 'apiVersion: apiextensions.k8s.io/v1' }
    
#    - name: modify 'snapshot.storage.k8s.io_volumesnapshots.yaml' file
#      lineinfile:
#        path: /home/jono/csi-vxflex/dell-csi-helm-installer/beta-snapshot-crd/snapshot.storage.k8s.io_volumesnapshots.yaml
#        regexp: '{{item.From}}'
#        line: '{{item.To}}'
#      with_items:
#        - { From: 'apiVersion: apiextensions.k8s.io/v1beta1', To: 'apiVersion: apiextensions.k8s.io/v1' }
      
    - name: copy snapshot-controller to master
      copy:
        src: /root/demo/snapshot-controller.yaml
        dest: /home/jono/snapshot-controller.yaml 
        mode: '0700'
      become: yes
      become_user: jono
    
    - name: copy csi-snapshotter to master
      copy:
        src: /root/demo/csi-snapshotter.yaml
        dest: /home/jono/csi-snapshotter.yaml 
        mode: '0700'
      become: yes
      become_user: jono
      
    - name: copy rbac-controller to master
      copy:
        src: /root/demo/rbac-controller.yaml
        dest: /home/jono/rbac-controller.yaml 
        mode: '0700'
      become: yes
      become_user: jono  
    
    - name: install snapshot-controller
      become: yes
      become_user: jono
      shell: kubectl apply -f /home/jono/snapshot-controller.yaml 
    
    - name: install csi-snapshotter
      become: yes
      become_user: jono
      shell: kubectl apply -f /home/jono/csi-snapshotter.yaml
    
    - name: install rbac-controller
      become: yes
      become_user: jono
      shell: kubectl apply -f /home/jono/rbac-controller.yaml 
      
    - name: install dummy sdc-repo-secret
      become: yes
      become_user: jono
      shell: kubectl create -f /home/jono/csi-vxflex/helm/sdc-repo-secret.yaml 
      
    - name: copy rbac-config to master
      copy:
        src: /root/demo/rbac-config.yaml
        dest: /home/jono/rbac-config.yaml 
        mode: '0700'
      become: yes
      become_user: jono

    - name: install rbac-config
      become: yes
      become_user: jono
      shell: kubectl create -f /home/jono/csi-vxflex/helm/rbac-config.yaml
      
    - name: update tiller
      become: yes
      become_user: jono
      shell: helm init --upgrade --service-account-tiller
