- hosts: master
  become: yes
  tasks: 
    - name: copy get_helm
      copy:
        src: /root/demo/get_helm.sh
        dest: /root/get_helm.sh
        mode: '0700'
        
    - name: run get_helm.sh
      shell: /root/get_helm.sh 
      
    - name: git clone csi-vxflex
      git:
        repo: https://github.com/dell/csi-vxflexos
        dest: /home/jono/csi-vxflex/
        accept_hostkey: yes
        key_file: /home/jono/.ssh/id_rsa
      become: yes
      become_user: jono
           
    - name: create vxflexos namespace
      become: yes
      become_user: jono
      shell: kubectl create namespace vxflexos
      
    - name: copy 'myvalues.yaml' file
      copy:
        src: /home/jono/csi-vxflex/helm/csi-vxflexos/values.yaml
        dest: /home/jono/csi-vxflex/helm/myvalues.yaml
        remote_src: yes
  
    - name: copy setup-snapshot-controller
      get_url:
        url: https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
        dest: /home/jono/setup-snapshot-controller.yaml
        mode: '0700'
      become: yes
      become_user: jono
    
    - name: copy rbac-snapshot-controller
      get_url:
        url: https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
        dest: /home/jono/rbac-snapshot-controller.yaml
        mode: '0700'
      become: yes
      become_user: jono
    
    - name: install setup-snapshot-controller
      become: yes
      become_user: jono
      shell: kubectl create -f /home/jono/setup-snapshot-controller.yaml
    
    - name: install rbac-snapshot-controller
      become: yes
      become_user: jono
      shell: kubectl create -f /home/jono/rbac-snapshot-controller.yaml 
         
    - name: copy config.json
      copy:
        src: /root/demo/config.json
        dest: /home/jono/config.json 
        mode: '0700'
      become: yes
      become_user: jono    
      
    - name: create secret
      become: yes
      become_user: jono
      shell: kubectl create secret generic vxflexos-config -n vxflexos --from-file=config=/home/jono/config.json
    
    - name: copy storageclass.yaml
      copy:
        src: /root/demo/storageclass.yaml
        dest: /home/jono/storageclass.yaml 
        mode: '0700'
      become: yes
      become_user: jono 
    
    - name: install storageclass.yaml
      become: yes
      become_user: jono
      shell: kubectl create -f /home/jono/storageclass.yaml
    
    - name: copy snapshot.storage.k8s.io_volumesnapshotclasses.yaml
      get_url:
        url: https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
        dest: /home/jono/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
        mode: '0700'
      become: yes
      become_user: jono
    
    - name: install snapshot.storage.k8s.io_volumesnapshotclasses.yaml
      become: yes
      become_user: jono
      shell: kubectl create -f /home/jono/snapshot.storage.k8s.io_volumesnapshotclasses.yaml  

    - name: copy snapshot.storage.k8s.io_volumesnapshotcontents.yaml
      get_url:
        url: https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
        dest: /home/jono/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
        mode: '0700'
      become: yes
      become_user: jono
       
    - name: install snapshot.storage.k8s.io_volumesnapshotcontents.yaml
      become: yes
      become_user: jono
      shell: kubectl create -f /home/jono/snapshot.storage.k8s.io_volumesnapshotcontents.yaml   
    
    - name: copy snapshot.storage.k8s.io_volumesnapshots.yaml
      get_url:
        url: https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.0.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
        dest: /home/jono/snapshot.storage.k8s.io_volumesnapshots.yaml
        mode: '0700'
      become: yes
      become_user: jono
    
    - name: install snapshot.storage.k8s.io_volumesnapshots.yaml
      become: yes
      become_user: jono
      shell: kubectl create -f /home/jono/snapshot.storage.k8s.io_volumesnapshots.yaml      
