apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vxflexos
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi-vxflexos.dellemc.com
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  storagepool: RSSDA   #Insert Storage pool.
  systemID: PowerFlex-SantaClara         #Insert System ID
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: csi-vxflexos.dellemc.com/PowerFlex-SantaClara   #Insert System ID
    values:
    - csi-vxflexos.dellemc.com